# https://github.com/caarlos0-graveyard/shell-ci-build
# https://github.com/kward/shunit2/blob/master/.travis.yml
language: bash

# The Ubuntu Linux Build Environments
#   https://docs.travis-ci.com/user/reference/linux/
# The macOS Build Environment
#   https://docs.travis-ci.com/user/reference/osx/
# Installing Dependencies
#   https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode11.3
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install coreutils
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install gnu-sed

script:
  - test-cases/integration-test.sh

after_script:
  - git status --ignored
