# https://github.com/caarlos0-graveyard/shell-ci-build
# https://github.com/kward/shunit2/blob/master/.travis.yml
language: bash

# The Ubuntu Linux Build Environments
#   https://docs.travis-ci.com/user/reference/linux/
# The macOS Build Environment
#   https://docs.travis-ci.com/user/reference/osx/
matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: osx

script:
  - test-cases/integration-test.sh

after_script:
  - git status --ignored
